STARTER_RECIPES = [
    {
        "title": "Easy Chicken Stir Fry",
        "category": "entree",
        "description": "Quick chicken stir fry with broccoli, peppers, carrots, and a honey-soy sauce.",
        "source_url": "https://www.momontimeout.com/easy-chicken-stir-fry-recipe/",
        "calories": 343,
        "carbs_grams": "29",
        "fat_grams": "13",
        "protein_grams": "26",
        "ingredients": [
            "1 lb boneless skinless chicken breast",
            "2 cups broccoli florets",
            "1/2 yellow bell pepper",
            "1/2 red bell pepper",
            "1/2 cup baby carrots",
            "2 tsp minced ginger",
            "2 garlic cloves",
            "1 tbsp corn starch",
            "2 tbsp cold water",
            "1/4 cup low sodium chicken broth",
            "3 tbsp low sodium soy sauce",
            "1/4 cup honey",
            "1 tbsp toasted sesame oil",
        ],
        "steps": [
            "Whisk the corn starch, water, broth, soy sauce, honey, and sesame oil into a stir fry sauce.",
            "Cook the chicken in oil until browned and cooked through, then set it aside.",
            "Cook the broccoli, peppers, carrots, ginger, and garlic until crisp-tender.",
            "Return the chicken to the pan, pour in the sauce, and simmer until thickened.",
        ],
    },
    {
        "title": "Chicken Parmesan",
        "category": "entree",
        "description": "Breaded chicken baked with tomato sauce, mozzarella, provolone, basil, and Parmesan.",
        "source_url": "https://www.allrecipes.com/recipe/223042/chicken-parmesan/",
        "calories": 471,
        "carbs_grams": "25",
        "fat_grams": "25",
        "protein_grams": "42",
        "ingredients": [
            "4 chicken breast halves",
            "2 large eggs",
            "1 cup panko bread crumbs",
            "3/4 cup grated Parmesan cheese",
            "2 tbsp all-purpose flour",
            "1/2 cup olive oil",
            "1/2 cup prepared tomato sauce",
            "1/4 cup fresh mozzarella",
            "1/4 cup chopped fresh basil",
            "1/2 cup grated provolone cheese",
        ],
        "steps": [
            "Pound the chicken to an even thickness and season with salt and pepper.",
            "Coat the chicken with flour, egg, and a panko-Parmesan mixture.",
            "Pan fry until golden on both sides.",
            "Top with sauce, mozzarella, basil, and provolone, then bake until cooked through.",
        ],
    },
    {
        "title": "Protein Pancakes",
        "category": "snack",
        "description": "Fluffy protein pancakes made with flour, whey protein, eggs, milk, and butter.",
        "source_url": "https://www.laurafuentes.com/protein-pancakes/",
        "calories": 292,
        "carbs_grams": "41",
        "fat_grams": "3",
        "protein_grams": "26",
        "ingredients": [
            "1 1/2 cups all-purpose flour",
            "1/2 cup vanilla whey protein powder",
            "2 1/2 tsp baking powder",
            "1 pinch salt",
            "1 1/2 cups milk",
            "2 large eggs",
            "2 tbsp melted butter",
            "1 tsp vanilla extract",
        ],
        "steps": [
            "Mix the flour, protein powder, baking powder, and salt.",
            "Whisk in the milk, eggs, butter, and vanilla until smooth.",
            "Cook 1/4 cup portions on a greased skillet until bubbles form, then flip.",
            "Serve warm with toppings of your choice.",
        ],
    },
    {
        "title": "Ground Beef Tacos",
        "category": "entree",
        "description": "Weeknight tacos with seasoned ground beef, tortillas, lettuce, tomatoes, and cheese.",
        "source_url": "https://feelgoodfoodie.net/recipe/ground-beef-tacos-napa-cabbage-guacamole/",
        "calories": 142,
        "carbs_grams": "13",
        "fat_grams": "4",
        "protein_grams": "14",
        "ingredients": [
            "1 tbsp olive oil",
            "1 lb lean ground beef",
            "2 tsp chili powder",
            "2 tsp cumin",
            "1/2 tsp oregano",
            "1/2 tsp garlic powder",
            "1/2 tsp salt",
            "1/2 tsp black pepper",
            "2 tbsp tomato paste",
            "1/2 cup water",
            "8 tortillas",
            "1 cup chopped lettuce",
            "1 cup chopped tomatoes",
            "1/2 cup shredded cheese",
            "1/4 cup chopped red onions",
        ],
        "steps": [
            "Brown the ground beef in olive oil and drain excess fat.",
            "Stir in the spices, tomato paste, and water until the meat is coated.",
            "Simmer until the sauce thickens.",
            "Serve in tortillas with lettuce, tomatoes, cheese, and red onions.",
        ],
    },
]
