# Generated by Django 6.0.3 on 2026-03-27 17:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('snack', 'Snack'), ('entree', 'Entree'), ('dessert', 'Dessert')], default='entree', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/')),
                ('external_image_url', models.URLField(blank=True)),
                ('source_url', models.URLField(blank=True)),
                ('calories', models.PositiveIntegerField(default=0)),
                ('carbs_grams', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=6)),
                ('fat_grams', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=6)),
                ('protein_grams', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=6)),
                ('is_starter', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(blank=True, max_length=150)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('unit', models.CharField(blank=True, max_length=40)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='planner.recipe')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='planner.recipe')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MealEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('slot', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('other', 'Other')], max_length=20)),
                ('custom_slot_name', models.CharField(blank=True, max_length=40)),
                ('quantity', models.DecimalField(decimal_places=1, default=Decimal('1.0'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.5'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_entries', to=settings.AUTH_USER_MODEL)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_entries', to='planner.recipe')),
            ],
            options={
                'ordering': ['date', 'slot', 'recipe__title'],
                'constraints': [models.UniqueConstraint(fields=('user', 'date', 'slot', 'recipe', 'custom_slot_name'), name='unique_recipe_per_slot_day')],
            },
        ),
    ]
